### ISSUE TITLE
Research biofilm growth on materials of strings

### ISSUE THREAD

**Issue by rosiekrasnoff** [AguaClara/String-Digester#23]
Biofilm growth on:
-polypropylene
-stainless steel
-nylon

**Comment by rosiekrasnoff** [comment]
potentially useful papers:
https://www.sciencedirect.com/science/article/pii/S0043135497003515
https://onlinelibrary.wiley.com/doi/full/10.1002/bit.24451
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732559/
https://web.wpi.edu/Pubs/E-project/Available/E-project-030212-075110/unrestricted/KlocMendoza_MQP.pdf
https://www.sciencedirect.com/science/article/pii/004313549090109J

**Comment by MadelineGarell** [comment]
https://www.researchgate.net/publication/275976424_Evaluation_of_Wastewater_Treatment_Efficiency_Using_Coconut_Fiber_Biofilm_Reactor_System_With_Synthetic_Leachate

**Comment by ZsofiaSzegletes** [comment]
https://www.jstage.jst.go.jp/article/jgam1955/31/2/31_2_177/_article/-char/ja/
